# Generated by Django 3.2.18 on 2023-03-09 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
