# Generated by Django 3.2.18 on 2023-03-15 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submited'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
