# Generated by Django 3.2.18 on 2023-03-20 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230315_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
