# Generated by Django 3.2.18 on 2023-03-25 19:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20230321_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
