# Generated by Django 3.2.18 on 2023-03-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_profile_user_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content_footer',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content2',
            new_name='content_header',
        ),
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(max_length=400, null=True),
        ),
    ]
