# Generated by Django 3.2.18 on 2023-03-31 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_comment_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='name',
        ),
    ]
